name: aiesec_core
description: A new Flutter project.
publish_to: "none"
version: 1.1.2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^5.0.0-release-candidate-4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  card_loading: ^0.3.0
  another_stepper: ^1.2.2
  url_launcher: ^6.1.12
  animated_list_item: ^1.0.0
  flutter_slidable: ^3.0.0
  android_path_provider: ^0.3.0
  fluttertoast: ^8.2.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
